DROP TABLE IF EXISTS resuls_P1_pighive.C2;

CREATE TABLE resuls_P1_pighive.C2
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n' AS

SELECT DISTINCT * FROM practicas.atletas WHERE Team='Spain' ORDER BY Name DESC;
